# !usr/bin/env python3
#  -*- coding:utf-8 -*-

import unittest
from htr.HTMLTestRunner import *
from api.access import *

from conf.config import Config

cfg = Config()


def login():
    return doRequest('/user/login', [{'name': 'admin', 'password': '123456'}])


def logout(accesstoken: str):
    return doRequest('/user/logout', [], headers={'accesstoken': accesstoken})


class LoginTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        loadApisDoc(cfg.doc_file)

    def test_login(self):
        r = login()
        self.assertEqual(r.status_code, 200)
        self.assertIsNotNone(r.json()['data']['token'])

        r2 = logout('')
        self.assertEqual(r2.status_code, 401)

        r4 = logout(r.json()['data']['token'])
        self.assertEqual(r4.status_code, 200)


if __name__ == '__main__':
    # unittest.main()

    suite = unittest.TestSuite()
    suite.addTest(LoginTest('test_login'))
    # suite.addTests(unittest.TestLoader().loadTestsFromTestCase(LoginTest))

    with open(cfg.doc_html, 'wb') as f:
        runner = HTMLTestRunner(stream=f,
                                title='Api Test Report',
                                description='generated by HTMLTestRunner.',
                                verbosity=2)
        runner.run(suite)
